# Generated by Django 5.2 on 2025-09-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='api_note_owner_i_d9f58a_idx',
            old_name='api_note_owner_i_e1a7b8_idx',
        ),
    ]
